# Generated by Django 2.2 on 2020-04-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_menus_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='menu_name',
            field=models.TextField(max_length=200, verbose_name='Menu'),
        ),
    ]
